name: 'Using GCHR Image'
description: 'Secure ALL the things!'

inputs:
  name:
    description: 'Who are we saying hello to?'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}